### ISSUE TITLE
3_Features_students : Caltech 101 download

### ISSUE THREAD

**Issue by CharlyGirotNYU** [rwth-lfb/MLL#1] opened 2020-10-15 12:18 UTC
ds = Caltech101(dset_path, download=True) throws exception "not a gzip file" 

Looks like there is an issue with the download of the Caltech101 dataset but can't figure out the root of the issue. 
Would anyone have an idea ? 

 --- Running on Docker (Windows Desktop) --- JupyterHub ---

Please find bellow the output exception of the previous code  : 
```
0it [00:00, ?it/s]
Downloading http://www.vision.caltech.edu/Image_Datasets/Caltech101/101_ObjectCategories.tar.gz to /home/praktikum/datasets/caltech101/101_ObjectCategories.tar.gz
65536it [00:00, 100393.46it/s]
0it [00:00, ?it/s]
Downloading http://www.vision.caltech.edu/Image_Datasets/Caltech101/Annotations.tar to /home/praktikum/datasets/caltech101/101_Annotations.tar
65536it [00:00, 100436.90it/s]
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/opt/conda/lib/python3.7/tarfile.py in gzopen(cls, name, mode, fileobj, compresslevel, **kwargs)
   1644         try:
-> 1645             t = cls.taropen(name, mode, fileobj, **kwargs)
   1646         except OSError:

/opt/conda/lib/python3.7/tarfile.py in taropen(cls, name, mode, fileobj, **kwargs)
   1620             raise ValueError("mode must be 'r', 'a', 'w' or 'x'")
-> 1621         return cls(name, mode, fileobj, **kwargs)
   1622 

/opt/conda/lib/python3.7/tarfile.py in __init__(self, name, mode, fileobj, format, tarinfo, dereference, ignore_zeros, encoding, errors, pax_headers, debug, errorlevel, copybufsize)
   1483                 self.firstmember = None
-> 1484                 self.firstmember = self.next()
   1485 

/opt/conda/lib/python3.7/tarfile.py in next(self)
   2288             try:
-> 2289                 tarinfo = self.tarinfo.fromtarfile(self)
   2290             except EOFHeaderError as e:

/opt/conda/lib/python3.7/tarfile.py in fromtarfile(cls, tarfile)
   1093         """
-> 1094         buf = tarfile.fileobj.read(BLOCKSIZE)
   1095         obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)

/opt/conda/lib/python3.7/gzip.py in read(self, size)
    275             raise OSError(errno.EBADF, "read() on write-only GzipFile object")
--> 276         return self._buffer.read(size)
    277 

/opt/conda/lib/python3.7/_compression.py in readinto(self, b)
     67         with memoryview(b) as view, view.cast("B") as byte_view:
---> 68             data = self.read(len(byte_view))
     69             byte_view[:len(data)] = data

/opt/conda/lib/python3.7/gzip.py in read(self, size)
    462                 self._init_read()
--> 463                 if not self._read_gzip_header():
    464                     self._size = self._pos

/opt/conda/lib/python3.7/gzip.py in _read_gzip_header(self)
    410         if magic != b'\037\213':
--> 411             raise OSError('Not a gzipped file (%r)' % magic)
    412 

OSError: Not a gzipped file (b'<!')

During handling of the above exception, another exception occurred:

ReadError                                 Traceback (most recent call last)
<ipython-input-66-cddeef386f24> in <module>
      4 dset_path = os.path.join(os.path.abspath(os.environ["HOME"]), 'datasets')
      5 #if not os.path.exists(os.path.join(dset_path, 'caltech101')):
----> 6 ds = Caltech101(dset_path, download=True)
      7 
      8 

/opt/conda/lib/python3.7/site-packages/torchvision/datasets/caltech.py in __init__(self, root, target_type, transform, target_transform, download)
     40 
     41         if download:
---> 42             self.download()
     43 
     44         if not self._check_integrity():

/opt/conda/lib/python3.7/site-packages/torchvision/datasets/caltech.py in download(self)
    126 
    127         # extract file
--> 128         with tarfile.open(os.path.join(self.root, "101_ObjectCategories.tar.gz"), "r:gz") as tar:
    129             tar.extractall(path=self.root)
    130 

/opt/conda/lib/python3.7/tarfile.py in open(cls, name, mode, fileobj, bufsize, **kwargs)
   1589             else:
   1590                 raise CompressionError("unknown compression type %r" % comptype)
-> 1591             return func(name, filemode, fileobj, **kwargs)
   1592 
   1593         elif "|" in mode:

/opt/conda/lib/python3.7/tarfile.py in gzopen(cls, name, mode, fileobj, compresslevel, **kwargs)
   1647             fileobj.close()
   1648             if mode == 'r':
-> 1649                 raise ReadError("not a gzip file")
   1650             raise
   1651         except:

ReadError: not a gzip file
```

**Comment by ORippler** [comment] 2021-04-12 15:20
This was caused by an outdated version of `torchvision`. Fixed in 6287bd4c65e06f95f4d698f9cf8de3093e94ca99

**Closed as completed by ORippler** 2021-04-12 15:20 UTC
